tv_items = [
    {
        "name": "Tmdb - Trending",
        "mode": "tv",
        "api": "tmdb",
        "query": "tmdb_trending",
        "icon": "tmdb.png",
    },
    {
        "name": "Tmdb - Genres",
        "mode": "tv",
        "api": "tmdb",
        "query": "tmdb_genres",
        "icon": "tmdb.png",
    },
    {
        "name": "Trakt - Trending",
        "mode": "tv",
        "api": "trakt",
        "query": "trakt_trending",
        "icon": "trakt.png",
    },
    {
        "name": "Trakt - Most Watched",
        "mode": "tv",
        "api": "trakt",
        "query": "trakt_watched",
        "icon": "trakt.png",
    },
    {
        "name": "Trakt - Most Favorited",
        "mode": "tv",
        "api": "trakt",
        "query": "trakt_favorited",
        "icon": "trakt.png",
    },
    {
        "name": "Trakt - Recomendations",
        "mode": "tv",
        "api": "trakt",
        "query": "trakt_recommendations",
        "icon": "trakt.png",
    },
    {
        "name": "Trakt - Trending Lists",
        "mode": "tv",
        "api": "trakt",
        "query": "trakt_trending_lists",
        "icon": "trakt.png",
    },
    {
        "name": "Trakt - Watchlist",
        "mode": "tv",
        "api": "trakt",
        "query": "trakt_watchlist",
        "icon": "trakt.png",
    },
]

movie_items = [
    {
        "name": "Tmdb - Trending",
        "mode": "movie",
        "api": "tmdb",
        "query": "tmdb_trending",
        "icon": "tmdb.png",
    },
    {
        "name": "Tmdb - Genres",
        "mode": "movie",
        "api": "tmdb",
        "query": "tmdb_genres",
        "icon": "tmdb.png",
    },
    {
        "name": "Trakt - Trending",
        "mode": "movie",
        "api": "trakt",
        "query": "trakt_trending",
        "icon": "trakt.png",
    },
    {
        "name": "Trakt - Top 10 BoxOffice",
        "mode": "movie",
        "api": "trakt",
        "query": "trakt_top10",
        "icon": "trakt.png",
    },
    {
        "name": "Trakt - Most Watched",
        "mode": "movie",
        "api": "trakt",
        "query": "trakt_watched",
        "icon": "trakt.png",
    },
    {
        "name": "Trakt - Most Favorited",
        "mode": "movie",
        "api": "trakt",
        "query": "trakt_favorited",
        "icon": "trakt.png",
    },
    {
        "name": "Trakt - Recomendations",
        "mode": "movie",
        "api": "trakt",
        "query": "trakt_recommendations",
        "icon": "trakt.png",
    },
    {
        "name": "Trakt - Trending Lists",
        "mode": "movie",
        "api": "trakt",
        "query": "trakt_trending_lists",
        "icon": "trakt.png",
    },
    {
        "name": "Trakt - Watchlist",
        "mode": "movie",
        "api": "trakt",
        "query": "trakt_watchlist",
        "icon": "trakt.png",
    },
]
