TOP_RATED_COLLECTIONS = [
    {"id": "119", "type": "movie", "name": "The Lord of the Rings Collection"},
    {"id": "230", "type": "movie", "name": "The Godfather Collection"},
    {"id": "263", "type": "movie", "name": "The Dark Knight Collection"},
    {"id": "573436", "type": "movie", "name": "Spider-Man: Spider-Verse Collection"},
    {"id": "726871", "type": "movie", "name": "Dune Collection"},
    {"id": "2883", "type": "movie", "name": "Kill Bill Collection"},
    {"id": "422837", "type": "movie", "name": "Blade Runner Collection"},
    {"id": "86311", "type": "movie", "name": "The Avengers Collection"},
    {"id": "10194", "type": "movie", "name": "Toy Story Collection"},
    {"id": "264", "type": "movie", "name": "Back to the Future Collection"},
    {"id": "530064", "type": "movie", "name": "The Shining Collection"},
    {"id": "1022790", "type": "movie", "name": "Inside Out Collection"},
    {"id": "284433", "type": "movie", "name": "Guardians of the Galaxy Collection"},
    {"id": "89137", "type": "movie", "name": "How to Train Your Dragon Collection"},
    {"id": "468222", "type": "movie", "name": "The Incredibles Collection"},
    {"id": "1241", "type": "movie", "name": "Harry Potter Collection"},
    {"id": "531241", "type": "movie", "name": "Spider-Man (MCU) Collection"},
    {"id": "137696", "type": "movie", "name": "Monsters, Inc. Collection"},
    {"id": "137697", "type": "movie", "name": "Finding Nemo Collection"},
    {"id": "448150", "type": "movie", "name": "Deadpool Collection"},
    {"id": "87096", "type": "movie", "name": "Avatar Collection"},
    {"id": "121938", "type": "movie", "name": "The Hobbit Collection"},
    {"id": "10", "type": "movie", "name": "Star Wars Collection"},
    {"id": "9743", "type": "movie", "name": "The Hannibal Lecter Collection"},
    {"id": "1069584", "type": "movie", "name": "Gladiator Collection"},
    {"id": "722971", "type": "movie", "name": "Knives Out Collection"},
    {"id": "404609", "type": "movie", "name": "John Wick Collection"},
    {"id": "102322", "type": "movie", "name": "Sherlock Holmes Collection"},
    {"id": "8091", "type": "movie", "name": "Alien Collection"},
    {"id": "84", "type": "movie", "name": "Indiana Jones Collection"},
    {"id": "131292", "type": "movie", "name": "Iron Man Collection"},
    {"id": "521226", "type": "movie", "name": "A Quiet Place Collection"},
    {"id": "94032", "type": "movie", "name": "The Lion King Collection"},
    {"id": "8945", "type": "movie", "name": "Mad Max Collection"},
    {"id": "618529", "type": "movie", "name": "Doctor Strange Collection"},
    {"id": "453993", "type": "movie", "name": "The Wolverine Collection"},
    {"id": "295", "type": "movie", "name": "Pirates of the Caribbean Collection"},
    {"id": "1241984", "type": "movie", "name": "Moana Collection"},
    {"id": "748", "type": "movie", "name": "X-Men Collection"},
    {"id": "556", "type": "movie", "name": "Spider-Man Collection"},
    {"id": "386382", "type": "movie", "name": "Frozen Collection"},
    {"id": "2344", "type": "movie", "name": "The Matrix Collection"},
    {"id": "528", "type": "movie", "name": "The Terminator Collection"},
    {"id": "131295", "type": "movie", "name": "Captain America Collection"},
    {"id": "131296", "type": "movie", "name": "Thor Collection"},
    {"id": "2150", "type": "movie", "name": "Shrek Collection"},
    {"id": "391860", "type": "movie", "name": "Kingsman Collection"},
    {"id": "131635", "type": "movie", "name": "The Hunger Games Collection"},
    {"id": "529892", "type": "movie", "name": "Black Panther Collection"},
    {"id": "477962", "type": "movie", "name": "It Collection"},
    {"id": "125570", "type": "movie", "name": "300 Collection"},
    {"id": "987044", "type": "movie", "name": "Joker Collection"},
    {"id": "382685", "type": "movie", "name": "Now You See Me Collection"},
    {"id": "645", "type": "movie", "name": "James Bond Collection"},
    {"id": "86066", "type": "movie", "name": "Despicable Me Collection"},
    {"id": "86055", "type": "movie", "name": "Men In Black"},
]


POPULAR_COLLECTIONS = [
    {"id": 1449595, "name": "Ne Zha Collection"},
    {"id": 1211317, "name": "Creation of the Gods Trilogy"},
    {"id": 328, "name": "Jurassic Park Collection"},
    {"id": 1071588, "name": "M3GAN Collection"},
    {"id": 1565, "name": "28 Days/Weeks Later Collection"},
    {"id": 1231053, "name": "The Bad Guys Collection"},
    {"id": 1129084, "name": "Nobody Collection"},
    {"id": 1156666, "name": "Fault Collection"},
    {"id": 8580, "name": "The Karate Kid Collection"},
    {"id": 870339, "name": "The Accountant Collection"},
    {"id": 1022790, "name": "Inside Out Collection"},
    {"id": 925155, "name": "Demon Slayer: Kimetsu no Yaiba Collection"},
    {"id": 8864, "name": "Final Destination Collection"},
    {"id": 87096, "name": "Avatar Collection"},
    {"id": 1241984, "name": "Moana Collection"},
    {"id": 531241, "name": "Spider-Man (MCU) Collection"},
    {"id": 86311, "name": "The Avengers Collection"},
    {"id": 87359, "name": "Mission: Impossible Collection"},
    {"id": 1241, "name": "Harry Potter Collection"},
    {"id": 762512, "name": "The Lion King (Reboot) Collection"},
    {"id": 448150, "name": "Deadpool Collection"},
    {"id": 720879, "name": "Sonic the Hedgehog Collection"},
    {"id": 119, "name": "The Lord of the Rings Collection"},
    {"id": 313086, "name": "The Conjuring Collection"},
    {"id": 89137, "name": "How to Train Your Dragon Collection"},
    {"id": 573436, "name": "Spider-Man: Spider-Verse Collection"},
    {"id": 131292, "name": "Iron Man Collection"},
    {"id": 390636, "name": "Fate/stay night: Heaven's Feel Collection"},
    {"id": 131295, "name": "Captain America Collection"},
    {"id": 263, "name": "The Dark Knight Collection"},
    {"id": 1069584, "name": "Gladiator Collection"},
    {"id": 230, "name": "The Godfather Collection"},
    {"id": 726871, "name": "Dune Collection"},
    {"id": 531330, "name": "Top Gun Collection"},
    {"id": 468552, "name": "Wonder Woman Collection"},
    {"id": 468222, "name": "The Incredibles Collection"},
    {"id": 295, "name": "Pirates of the Caribbean Collection"},
    {"id": 2150, "name": "Shrek Collection"},
    {"id": 556, "name": "Spider-Man Collection"},
    {"id": 86066, "name": "Despicable Me Collection"},
    {"id": 404609, "name": "John Wick Collection"},
    {"id": 295130, "name": "The Maze Runner Collection"},
    {"id": 77816, "name": "Kung Fu Panda Collection"},
    {"id": 10194, "name": "Toy Story Collection"},
    {"id": 121938, "name": "The Hobbit Collection"},
    {"id": 618529, "name": "Doctor Strange Collection"},
    {"id": 523855, "name": "The Equalizer Collection"},
    {"id": 284433, "name": "Guardians of the Galaxy Collection"},
    {"id": 386382, "name": "Frozen Collection"},
    {"id": 420, "name": "The Chronicles of Narnia Collection"},
    {"id": 11716, "name": "Addams Family Collection"},
    {"id": 987044, "name": "Joker Collection"},
    {"id": 86119, "name": "The Hangover Collection"},
    {"id": 531242, "name": "Suicide Squad Collection"},
    {"id": 529892, "name": "Black Panther Collection"},
    {"id": 422837, "name": "Blade Runner Collection"},
    {"id": 8091, "name": "Alien Collection"},
    {"id": 135483, "name": "Taken Collection"},
    {"id": 131296, "name": "Thor Collection"},
    {"id": 137696, "name": "Monsters, Inc. Collection"},
    {"id": 173710, "name": "Planet of the Apes (Reboot) Collection"},
    {"id": 477962, "name": "It Collection"},
    {"id": 94602, "name": "Puss in Boots Collection"},
    {"id": 37139, "name": "Naked Gun Collection"},
    {"id": 2344, "name": "The Matrix Collection"},
    {"id": 553717, "name": "Creed Collection"},
    {"id": 702624, "name": "After Collection"},
    {"id": 528, "name": "The Terminator Collection"},
    {"id": 619537, "name": "Train to Busan Collection"},
    {"id": 94032, "name": "The Lion King Collection"},
    {"id": 14890, "name": "Bad Boys Collection"},
    {"id": 399, "name": "Predator Collection"},
    {"id": 619802, "name": "The Roundup Collection"},
    {"id": 137697, "name": "Finding Nemo Collection"},
    {"id": 10, "name": "Star Wars Collection"},
    {"id": 544670, "name": "Sing Collection"},
    {"id": 264, "name": "Back to the Future Collection"},
    {"id": 185103, "name": "Hotel Transylvania Collection"},
    {"id": 87236, "name": "Mulan Collection"},
    {"id": 8354, "name": "Ice Age Collection"},
    {"id": 8945, "name": "Mad Max Collection"},
    {"id": 1268789, "name": "Tangled Collection"},
    {"id": 822306, "name": "Miraculous World"},
    {"id": 117777, "name": "Undisputed Collection"},
    {"id": 683698, "name": "Z-O-M-B-I-E-S Collection"},
    {"id": 530064, "name": "The Shining Collection"},
    {"id": 99606, "name": "Mean Girls Collection"},
    {"id": 9485, "name": "The Fast and the Furious Collection"},
    {"id": 153010, "name": "Beauty and the Beast Collection"},
    {"id": 8537, "name": "Superman Collection"},
    {"id": 55419, "name": "Cinderella Collection"},
    {"id": 97461, "name": "Lilo & Stitch Collection"},
    {"id": 1506082, "name": "The Vengeance Trilogy"},
    {"id": 2366, "name": "Jaws Collection"},
    {"id": 748, "name": "X-Men Collection"},
]
